#!/usr/bin/env bash
# Affiche toutes les IPv4 actives, une par ligne

if command -v ip >/dev/null 2>&1; then
  ip -o -4 addr show | awk '{print $4}' | cut -d/ -f1
elif command -v hostname >/dev/null 2>&1; then
  hostname -I 2>/dev/null | tr ' ' '\n' | awk '!/:/'
else
  ifconfig 2>/dev/null | awk '/inet /{print $2}' | sed 's/addr://'
fi
